---
title: "La transparence est-elle la solution aux différents problèmes de publication et prépublication rencontrés en contexte d’accélération de la recherche scientifique?"
author: "Nadia Tardy"
date: '2022-05-01'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


**En contexte d’accélération scientifique la prépublication d’articles est à son paroxysme. Plusieurs publications potentiellement erronées, incomplètes ou mal interprétées peuvent se retrouver au cœur de discussions médiatiques et influencer l’opinion publique, les actions gouvernementales et la pratique clinique. La transparence des études peut permettre d’atténuer les conséquences de ces articles, notamment car elle est à la base de la reproductibilité et de la réplicabilité. En contexte pandémique, on observe beaucoup de petites études indépendantes avec de petits échantillons. La transparence des études peut permettre une analyse par la communauté scientifique et permettre de répliquer l'étude avec un plus grand échantillon.**

En temps d’accélération de la recherche scientifique, par exemple relativement à la COVID-19, les différents journaux scientifiques peinent à publier les nombreux articles qui leur sont soumis à cause de leur processus assez fastidieux de vérification par les pairs. Les différents chercheurs se sont donc tournés vers des sites de prépublication qui approuvent les études en quelques jours, plutôt qu’en plusieurs mois comme c’est le cas des journaux où il y a révision par les pairs (Bilodeau 2021). Les articles publiés dans des sites de prépublication n’ont donc pas subit de processus de révision et peuvent comporter des données ou résultats erronés, incomplets ou mal interprétés. Ces articles qui ne sont pas révisés par les pairs peuvent susciter de fortes discussions dans les médias et réseaux sociaux (Vlasschaert & al. 2020; Martins & al. 2020) et peuvent aussi influencer l’opinion publique, les actions gouvernementales et la pratique clinique, pouvant ainsi entraîner des risques. La transparence, définie par la communication explicite, claire et ouverte des méthodes utilisées pour obtenir les résultats d’une étude (Bakken 2019) peut permettre de mitiger les conséquences de ces prépublications (Pundi & al. 2020). La transparence est à la base de la reproductibilité, définie comme la capacité à obtenir les mêmes résultats à partir des données et de la réplicabilité, définie comme la capacité d’autres scientifiques à observer les mêmes résultats dans des conditions identiques (Bakken 2019). 

La transparence dans les études est d’autant plus cruciale en contexte d’accélération des recherches scientifiques alors que la prépublication d’articles est en très forte hausse. 

Les sites de prépublication peuvent permettre un accès rapide à l’information en contexte d’accélération de la recherche scientifique et peuvent être des lieux de révision par les pairs puisque différents experts peuvent lire l’article et soulever des faiblesses et raccourcis à corriger (Bilodeau 2021), mais pour ce faire, la transparence est importante. En effet, l’absence de transparence empêche les autres scientifiques de reproduire l’étude afin de pouvoir en vérifier les résultats et les grandes lignes ressortant de l’étude (Jalali & al. 2020).  De plus, en ces temps de pandémie, il y a beaucoup de petits articles scientifiques qui sortent, avec de petits échantillons (Bonini & Maltese 2020). Il semble donc important de pouvoir vérifier les données, analyses et résultats de ces études. Par exemple, une inquiétude a été soulevée quant à certaines personnes qui revenaient dans plusieurs études, ce qui peut causer des inexactitudes dans la littérature scientifique et ainsi causer des biais dans les estimés, notamment quant à la prévalence de la maladie. Ce type de biais peut non seulement affecter la compréhension et l’épidémiologie de la maladie, mais a également le potentiel de résulter en des réponses de santé publique inadéquates, exacerber les conséquences économiques de la pandémie et accentuer l’anxiété dans la population (Bauchner & al. 2020). Cette présence de certaines personnes qui revenaient dans plusieurs études n’avait pas été mentionnée lors du dépôt du manuscrit. 

L’accélération de l’approbation d’articles scientifiques peut également mener à la parution d’articles qui ne respectaient pas les standards de révision par les pairs. L’exemple d’une étude sur l’hydroxychloroquine, publiée dans la revue scientifique *The Lancet* puis retirée (Mehra & al. 2020) a accentué les discussions sur l’importance de la transparences et l’accélération de publications en temps de COVID-19 (Bilodeau 2021).  Le problème principal qui avait d’ailleurs dérangé était le manque de transparence des auteurs quant à l’ensemble de leurs données. Les différents scientifiques se questionnent à savoir s’il s’agit d’une arnaque (Lapointe 2020). Différents faits ressortant de cette étude potentiellement frauduleuse avaient été utilisés dans les médias (Krause & al. [en impression]), propageant ainsi de la désinformation parmi la population. 

L’augmentation fulgurante et l’accélération de la publication d’articles dans un contexte d’accélération de la recherche scientifique pose donc des problèmes quant à l’exactitude des études et résultats et la désinformation pouvant être véhiculée dans la société des suites d’études inexactes. En temps de pandémie, plusieurs petites études indépendantes tendent à être produites avec de petits échantillons. La transparence des études peut permettre d’atténuer certains des problèmes soulevés précédemment. En effet, la transparence peut notamment permettre à la communauté scientifique de vérifier l’analyse et les résultats des études publiées sur des sites de prépublication. De plus, la transparence peut permettre à divers scientifiques de reproduire une étude, par exemple en utilisant un plus grand échantillon que l’étude initiale afin de tenter de répliquer et confirmer les observations d’une étude. La transparence est essentielle à la reproductibilité et la réplicabilité d’une étude et semble d’une importance accrue en contexte de recherche scientifique où la révision par les pairs ne subvient plus à la demande et que les scientifiques se tournent plus que jamais vers les sites de prépublication. 


**Bibliographie**

   Bakken, S. (2019). The journey to transparency, reproductibility, and replicability. *Journal of the American Medical Informatics Association, 26*(3), 185-187.
   
   Bauchner, H., Golub, R. M., & Zylke, J. (2020). Editorial concern—possible reporting of the same patients with COVID-19 in different reports. *Jama, 323*(13), 1256-1256.
   
   Bilodeau, M. (2021). *Des études trop rapides en temps de COVID?* Agence Science Presse. https://www.scientifique-en-chef.gouv.qc.ca/impacts/ddr-des-etudes-trop-rapides-en-temps-de-covid/
   
   Bonini, S., & Maltese, G. (2020). COVID-19 Clinical trials : quality matters more than quantity. *Allergy, 75*(10), 2542-2547.
   
   Jalali, M. S., DiGennaro, C., & Sridhar, D. (2020). Transparency assessment of COVID-19 models. *The Lancet Global Health, 8*(12), e1459-e1460.
   
   Krause, N. M., Freiling, I., & Scheufele, D. A. (en impression). The ‘infodemic’ infodemic: Toward a more nuanced understanding of Truth-claims and the need for (not) combatting misinformation. *The ANNALS of the American Academy of Political and Social Science*.
   
   Lapointe, P. (2020). *Rétractation d’articles et «Lancetgate»*. Agence Science Presse. https://www.sciencepresse.qc.ca/actualite/2020/06/04/retractation-articles-lancetgate
   
   Martins, R. S., Cheema, D. A., & Sohail, M. R. (2020). The pandemic of publications: are we sacrificing quality for quantity?. *Mayo Clinic Proceedings. 95*(10), 2288-2290.
   
   Mehra, M. P., Ruschitzka, F. & Patel, A. N. (2020).  Retractation—hydroxychloroquine or chloroquine with or without a macrolide for treatment of COVID-19: a multinational registry analysis. *The Lancet, 395*(10240), 1820.
   
   Pundi, K., Perino, A. C., Harrington, R. A. Krumholz, H. M., & Turakhia, M. P. (2020). Characteristics and strength of evidence of COVID-19 studies registered on ClinicalTrials.gov. *JAMA internal medicine, 180*(10), 1398-1400.
   
   Vlasschaert, C., Topf, J. M., & Hiremath, S. (2020). Proliferation of papers and preprints during the coronavirus disease 2019 pandemic: progress or problems with peer review?. *Advances in chronic kidney disease, 27*(5), 418-426. 